// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rangeAnomalyDetection
List rangeAnomalyDetection(DataFrame df, Nullable<List> value_ranges);
RcppExport SEXP _SA24204124_rangeAnomalyDetection(SEXP dfSEXP, SEXP value_rangesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< Nullable<List> >::type value_ranges(value_rangesSEXP);
    rcpp_result_gen = Rcpp::wrap(rangeAnomalyDetection(df, value_ranges));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SA24204124_rangeAnomalyDetection", (DL_FUNC) &_SA24204124_rangeAnomalyDetection, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_SA24204124(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
