# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title rangeAnomalyDetection
#' @description Outlier detection by range
#' @param df data to be detected if there are outliers, type of data frame
#' @param value_ranges data out of this normal range will be extracted, IQR(interquantile range) by default.
#' @return a list, including the index of anomaly, and the range.
#' @examples
#' \dontrun{
#' df2 <- data.frame(
#' d1 = runif(10, -30, 40),
#' d2 = runif(10, 900, 1100)
#' )
#' rangeAnomalyDetection(df2, value_ranges)
#' }
#' @export
rangeAnomalyDetection <- function(df, value_ranges = NULL) {
    .Call('_SA24204124_rangeAnomalyDetection', PACKAGE = 'SA24204124', df, value_ranges)
}

